import type { IconMap } from '~/types'

/**
 * griddy icon provider.
 *
 * Mapped against Iconify `griddy-icons` with `widget` fallback for missing glyphs.
 * Regenerate candidates: `node scripts/icons/build-provider-maps.mjs`
 */
export const griddyIconMap: IconMap = {
  'arrow-down': 'i-griddy-icons-arrow-down',
  'arrow-left': 'i-griddy-icons-arrow-left',
  'arrow-right': 'i-griddy-icons-arrow-right',
  'arrow-up': 'i-griddy-icons-arrow-up',
  bell: 'i-griddy-icons-notification',
  bolt: 'i-griddy-icons-flash',
  card: 'i-griddy-icons-credit-card',
  chart: 'i-griddy-icons-chart-bar',
  check: 'i-griddy-icons-check',
  'check-circle': 'i-griddy-icons-check-circle',
  checks: 'i-griddy-icons-check-double',
  'chevron-down': 'i-griddy-icons-chevron-down',
  'chevron-right': 'i-griddy-icons-chevron-right',
  clock: 'i-griddy-icons-time',
  close: 'i-griddy-icons-close',
  'close-circle': 'i-griddy-icons-close-circle',
  code: 'i-griddy-icons-code',
  'danger-triangle': 'i-griddy-icons-alert-triangle',
  database: 'i-griddy-icons-database',
  document: 'i-griddy-icons-file-text',
  'document-add': 'i-griddy-icons-file-plus',
  dollar: 'i-griddy-icons-currency-dollar',
  'dots-menu': 'i-griddy-icons-more-horizontal',
  download: 'i-griddy-icons-download',
  edit: 'i-griddy-icons-edit',
  emoji: 'i-griddy-icons-face-smile',
  file: 'i-griddy-icons-file',
  folder: 'i-griddy-icons-folder-open',
  graph: 'i-griddy-icons-trend-up',
  grid: 'i-griddy-icons-grid',
  home: 'i-griddy-icons-home',
  'info-circle': 'i-griddy-icons-info-circle',
  layers: 'i-griddy-icons-layers',
  letter: 'i-griddy-icons-email',
  list: 'i-griddy-icons-list-bulleted',
  lock: 'i-griddy-icons-lock',
  login: 'i-griddy-icons-log-in',
  logout: 'i-griddy-icons-log-out',
  menu: 'i-griddy-icons-menu',
  'minus-circle': 'i-griddy-icons-minus-circle',
  monitor: 'i-griddy-icons-monitor',
  moon: 'i-griddy-icons-moon',
  palette: 'i-griddy-icons-colors',
  'palette-round': 'i-griddy-icons-paint-brush',
  refresh: 'i-griddy-icons-refresh-cw',
  rocket: 'i-griddy-icons-rocket',
  search: 'i-griddy-icons-search',
  send: 'i-griddy-icons-send',
  settings: 'i-griddy-icons-settings',
  'shield-check': 'i-griddy-icons-shield-check',
  'shield-user': 'i-griddy-icons-shield-person',
  'shield-warning': 'i-griddy-icons-shield-alert',
  'shopping-cart': 'i-griddy-icons-shopping-bag',
  sidebar: 'i-griddy-icons-sidebar',
  spinner: 'i-griddy-icons-refresh',
  star: 'i-griddy-icons-star',
  sun: 'i-griddy-icons-sun',
  'trend-up': 'i-griddy-icons-trend-up',
  truck: 'i-griddy-icons-truck',
  tuning: 'i-griddy-icons-tune-horizontal',
  'user-plus': 'i-griddy-icons-user-plus',
  users: 'i-griddy-icons-users',
  widget: 'i-griddy-icons-layout',
  'zoom-in': 'i-griddy-icons-search-plus',
  'zoom-out': 'i-griddy-icons-search-minus',
}
