import type { IconMap } from '~/types'

/**
 * iconamoon icon provider.
 *
 * Mapped against Iconify `iconamoon` with `widget` fallback for missing glyphs.
 * Regenerate candidates: `node scripts/icons/build-provider-maps.mjs`
 */
export const iconamoonIconMap: IconMap = {
  'arrow-down': 'i-iconamoon-arrow-down-1',
  'arrow-left': 'i-iconamoon-arrow-left-1',
  'arrow-right': 'i-iconamoon-arrow-right-1',
  'arrow-up': 'i-iconamoon-arrow-up-1',
  bell: 'i-iconamoon-notification',
  bolt: 'i-iconamoon-lightning-1',
  card: 'i-iconamoon-credit-card',
  chart: 'i-iconamoon-apps',
  check: 'i-iconamoon-check',
  'check-circle': 'i-iconamoon-check-circle-1',
  checks: 'i-iconamoon-check',
  'chevron-down': 'i-iconamoon-arrow-down-2',
  'chevron-right': 'i-iconamoon-arrow-right-2',
  clock: 'i-iconamoon-clock',
  close: 'i-iconamoon-close',
  'close-circle': 'i-iconamoon-close-circle-1',
  code: 'i-iconamoon-apps',
  'danger-triangle': 'i-iconamoon-attention-circle',
  database: 'i-iconamoon-box',
  document: 'i-iconamoon-file-document',
  'document-add': 'i-iconamoon-file-add',
  dollar: 'i-iconamoon-apps',
  'dots-menu': 'i-iconamoon-menu-kebab-horizontal',
  download: 'i-iconamoon-download',
  edit: 'i-iconamoon-pen',
  emoji: 'i-iconamoon-smiling-face',
  file: 'i-iconamoon-file',
  folder: 'i-iconamoon-folder',
  graph: 'i-iconamoon-trend-up',
  grid: 'i-iconamoon-apps',
  home: 'i-iconamoon-home',
  'info-circle': 'i-iconamoon-information-circle',
  layers: 'i-iconamoon-component',
  letter: 'i-iconamoon-email',
  list: 'i-iconamoon-playlist',
  lock: 'i-iconamoon-lock',
  login: 'i-iconamoon-enter',
  logout: 'i-iconamoon-exit',
  menu: 'i-iconamoon-menu-burger-horizontal',
  'minus-circle': 'i-iconamoon-sign-minus-circle',
  monitor: 'i-iconamoon-apps',
  moon: 'i-iconamoon-mode-dark',
  palette: 'i-iconamoon-apps',
  'palette-round': 'i-iconamoon-apps',
  refresh: 'i-iconamoon-synchronize',
  rocket: 'i-iconamoon-apps',
  search: 'i-iconamoon-search',
  send: 'i-iconamoon-send',
  settings: 'i-iconamoon-settings',
  'shield-check': 'i-iconamoon-shield-yes',
  'shield-user': 'i-iconamoon-shield',
  'shield-warning': 'i-iconamoon-shield-no',
  'shopping-cart': 'i-iconamoon-shopping-card',
  sidebar: 'i-iconamoon-apps',
  spinner: 'i-iconamoon-restart',
  star: 'i-iconamoon-star',
  sun: 'i-iconamoon-mode-light',
  'trend-up': 'i-iconamoon-trend-up',
  truck: 'i-iconamoon-delivery',
  tuning: 'i-iconamoon-options',
  'user-plus': 'i-iconamoon-profile-circle',
  users: 'i-iconamoon-profile',
  widget: 'i-iconamoon-category',
  'zoom-in': 'i-iconamoon-zoom-in',
  'zoom-out': 'i-iconamoon-zoom-out',
}
