import type { IconMap } from '~/types'

/**
 * iconoir icon provider.
 *
 * Mapped against Iconify `iconoir` with `widget` fallback for missing glyphs.
 * Regenerate candidates: `node scripts/icons/build-provider-maps.mjs`
 */
export const iconoirIconMap: IconMap = {
  'arrow-down': 'i-iconoir-arrow-down',
  'arrow-left': 'i-iconoir-arrow-left',
  'arrow-right': 'i-iconoir-arrow-right',
  'arrow-up': 'i-iconoir-arrow-up',
  bell: 'i-iconoir-bell',
  bolt: 'i-iconoir-flash',
  card: 'i-iconoir-credit-card',
  chart: 'i-iconoir-stats-report',
  check: 'i-iconoir-check',
  'check-circle': 'i-iconoir-check-circle',
  checks: 'i-iconoir-double-check',
  'chevron-down': 'i-iconoir-nav-arrow-down',
  'chevron-right': 'i-iconoir-nav-arrow-right',
  clock: 'i-iconoir-clock',
  close: 'i-iconoir-xmark',
  'close-circle': 'i-iconoir-xmark-circle',
  code: 'i-iconoir-code',
  'danger-triangle': 'i-iconoir-warning-triangle',
  database: 'i-iconoir-database',
  document: 'i-iconoir-page',
  'document-add': 'i-iconoir-page-plus',
  dollar: 'i-iconoir-dollar',
  'dots-menu': 'i-iconoir-more-horiz',
  download: 'i-iconoir-download',
  edit: 'i-iconoir-edit',
  emoji: 'i-iconoir-emoji',
  file: 'i-iconoir-empty-page',
  folder: 'i-iconoir-folder',
  graph: 'i-iconoir-graph-up',
  grid: 'i-iconoir-view-grid',
  home: 'i-iconoir-home',
  'info-circle': 'i-iconoir-info-circle',
  layers: 'i-iconoir-multiple-pages',
  letter: 'i-iconoir-mail',
  list: 'i-iconoir-list',
  lock: 'i-iconoir-lock',
  login: 'i-iconoir-log-in',
  logout: 'i-iconoir-log-out',
  menu: 'i-iconoir-menu',
  'minus-circle': 'i-iconoir-minus-circle',
  monitor: 'i-iconoir-computer',
  moon: 'i-iconoir-half-moon',
  palette: 'i-iconoir-palette',
  'palette-round': 'i-iconoir-color-wheel',
  refresh: 'i-iconoir-refresh',
  rocket: 'i-iconoir-rocket',
  search: 'i-iconoir-search',
  send: 'i-iconoir-send',
  settings: 'i-iconoir-settings',
  'shield-check': 'i-iconoir-shield-check',
  'shield-user': 'i-iconoir-shield',
  'shield-warning': 'i-iconoir-shield-alert',
  'shopping-cart': 'i-iconoir-cart',
  sidebar: 'i-iconoir-sidebar-collapse',
  spinner: 'i-iconoir-refresh-circle',
  star: 'i-iconoir-star',
  sun: 'i-iconoir-sun-light',
  'trend-up': 'i-iconoir-graph-up',
  truck: 'i-iconoir-truck',
  tuning: 'i-iconoir-filter',
  'user-plus': 'i-iconoir-user-plus',
  users: 'i-iconoir-group',
  widget: 'i-iconoir-view-grid',
  'zoom-in': 'i-iconoir-zoom-in',
  'zoom-out': 'i-iconoir-zoom-out',
}
