import type { IconMap } from '~/types'

/**
 * mingcute icon provider.
 *
 * Mapped against Iconify `mingcute` with `widget` fallback for missing glyphs.
 * Regenerate candidates: `node scripts/icons/build-provider-maps.mjs`
 */
export const mingcuteIconMap: IconMap = {
  'arrow-down': 'i-mingcute-arrow-down-line',
  'arrow-left': 'i-mingcute-arrow-left-line',
  'arrow-right': 'i-mingcute-arrow-right-line',
  'arrow-up': 'i-mingcute-arrow-up-line',
  bell: 'i-mingcute-bell-ringing-line',
  bolt: 'i-mingcute-flash-line',
  card: 'i-mingcute-bank-card-line',
  chart: 'i-mingcute-chart-bar-line',
  check: 'i-mingcute-check-line',
  'check-circle': 'i-mingcute-check-circle-line',
  checks: 'i-mingcute-check-line',
  'chevron-down': 'i-mingcute-down-line',
  'chevron-right': 'i-mingcute-right-line',
  clock: 'i-mingcute-clock-line',
  close: 'i-mingcute-close-line',
  'close-circle': 'i-mingcute-close-circle-line',
  code: 'i-mingcute-code-line',
  'danger-triangle': 'i-mingcute-alert-line',
  database: 'i-mingcute-server-line',
  document: 'i-mingcute-document-line',
  'document-add': 'i-mingcute-file-new-line',
  dollar: 'i-mingcute-currency-dollar-line',
  'dots-menu': 'i-mingcute-more-1-line',
  download: 'i-mingcute-download-line',
  edit: 'i-mingcute-pencil-line',
  emoji: 'i-mingcute-emoji-line',
  file: 'i-mingcute-file-line',
  folder: 'i-mingcute-folder-open-line',
  graph: 'i-mingcute-trending-up-line',
  grid: 'i-mingcute-grid-line',
  home: 'i-mingcute-home-1-line',
  'info-circle': 'i-mingcute-information-line',
  layers: 'i-mingcute-layers-line',
  letter: 'i-mingcute-mail-line',
  list: 'i-mingcute-list-ordered-line',
  lock: 'i-mingcute-lock-line',
  login: 'i-mingcute-entrance-line',
  logout: 'i-mingcute-exit-line',
  menu: 'i-mingcute-menu-line',
  'minus-circle': 'i-mingcute-minus-circle-line',
  monitor: 'i-mingcute-monitor-line',
  moon: 'i-mingcute-moon-line',
  palette: 'i-mingcute-palette-line',
  'palette-round': 'i-mingcute-brush-line',
  refresh: 'i-mingcute-refresh-1-line',
  rocket: 'i-mingcute-rocket-line',
  search: 'i-mingcute-search-line',
  send: 'i-mingcute-send-line',
  settings: 'i-mingcute-settings-1-line',
  'shield-check': 'i-mingcute-safety-certificate-line',
  'shield-user': 'i-mingcute-shield-shape-line',
  'shield-warning': 'i-mingcute-warning-line',
  'shopping-cart': 'i-mingcute-shopping-cart-1-line',
  sidebar: 'i-mingcute-layout-left-line',
  spinner: 'i-mingcute-loading-line',
  star: 'i-mingcute-star-line',
  sun: 'i-mingcute-sun-line',
  'trend-up': 'i-mingcute-trending-up-line',
  truck: 'i-mingcute-truck-line',
  tuning: 'i-mingcute-settings-3-line',
  'user-plus': 'i-mingcute-user-add-line',
  users: 'i-mingcute-group-line',
  widget: 'i-mingcute-layout-grid-line',
  'zoom-in': 'i-mingcute-zoom-in-line',
  'zoom-out': 'i-mingcute-zoom-out-line',
}
