import type { IconMap } from '~/types'

/**
 * remix icon provider.
 *
 * Mapped against Iconify `ri` with `widget` fallback for missing glyphs.
 * Regenerate candidates: `node scripts/icons/build-provider-maps.mjs`
 */
export const remixIconMap: IconMap = {
  'arrow-down': 'i-ri-arrow-down-line',
  'arrow-left': 'i-ri-arrow-left-line',
  'arrow-right': 'i-ri-arrow-right-line',
  'arrow-up': 'i-ri-arrow-up-line',
  bell: 'i-ri-bell-line',
  bolt: 'i-ri-flashlight-line',
  card: 'i-ri-bank-card-2-line',
  chart: 'i-ri-bar-chart-line',
  check: 'i-ri-check-line',
  'check-circle': 'i-ri-checkbox-circle-line',
  checks: 'i-ri-check-double-line',
  'chevron-down': 'i-ri-arrow-down-s-line',
  'chevron-right': 'i-ri-arrow-right-s-line',
  clock: 'i-ri-time-line',
  close: 'i-ri-close-line',
  'close-circle': 'i-ri-close-circle-line',
  code: 'i-ri-code-line',
  'danger-triangle': 'i-ri-alert-line',
  database: 'i-ri-database-line',
  document: 'i-ri-file-text-line',
  'document-add': 'i-ri-file-add-line',
  dollar: 'i-ri-money-dollar-circle-line',
  'dots-menu': 'i-ri-more-line',
  download: 'i-ri-download-line',
  edit: 'i-ri-pencil-line',
  emoji: 'i-ri-emotion-line',
  file: 'i-ri-file-line',
  folder: 'i-ri-folder-open-line',
  graph: 'i-ri-line-chart-line',
  grid: 'i-ri-grid-line',
  home: 'i-ri-home-line',
  'info-circle': 'i-ri-information-line',
  layers: 'i-ri-stack-line',
  letter: 'i-ri-mail-line',
  list: 'i-ri-list-unordered',
  lock: 'i-ri-lock-line',
  login: 'i-ri-login-box-line',
  logout: 'i-ri-logout-box-line',
  menu: 'i-ri-menu-line',
  'minus-circle': 'i-ri-indeterminate-circle-line',
  monitor: 'i-ri-computer-line',
  moon: 'i-ri-moon-line',
  palette: 'i-ri-palette-line',
  'palette-round': 'i-ri-palette-line',
  refresh: 'i-ri-refresh-line',
  rocket: 'i-ri-rocket-line',
  search: 'i-ri-search-line',
  send: 'i-ri-send-plane-line',
  settings: 'i-ri-settings-line',
  'shield-check': 'i-ri-shield-check-line',
  'shield-user': 'i-ri-shield-user-line',
  'shield-warning': 'i-ri-shield-cross-line',
  'shopping-cart': 'i-ri-shopping-cart-line',
  sidebar: 'i-ri-side-bar-line',
  spinner: 'i-ri-loader-2-line',
  star: 'i-ri-star-line',
  sun: 'i-ri-sun-line',
  'trend-up': 'i-ri-line-chart-line',
  truck: 'i-ri-truck-line',
  tuning: 'i-ri-settings-3-line',
  'user-plus': 'i-ri-user-add-line',
  users: 'i-ri-group-line',
  widget: 'i-ri-layout-grid-line',
  'zoom-in': 'i-ri-zoom-in-line',
  'zoom-out': 'i-ri-zoom-out-line',
}
