import type { IconMap } from '~/types'

/**
 * tabler icon provider.
 *
 * Mapped against Iconify `tabler` with `widget` fallback for missing glyphs.
 * Regenerate candidates: `node scripts/icons/build-provider-maps.mjs`
 */
export const tablerIconMap: IconMap = {
  'arrow-down': 'i-tabler-arrow-down',
  'arrow-left': 'i-tabler-arrow-left',
  'arrow-right': 'i-tabler-arrow-right',
  'arrow-up': 'i-tabler-arrow-up',
  bell: 'i-tabler-bell',
  bolt: 'i-tabler-bolt',
  card: 'i-tabler-credit-card',
  chart: 'i-tabler-chart-bar',
  check: 'i-tabler-check',
  'check-circle': 'i-tabler-circle-check',
  checks: 'i-tabler-checks',
  'chevron-down': 'i-tabler-chevron-down',
  'chevron-right': 'i-tabler-chevron-right',
  clock: 'i-tabler-clock',
  close: 'i-tabler-x',
  'close-circle': 'i-tabler-circle-x',
  code: 'i-tabler-code',
  'danger-triangle': 'i-tabler-alert-triangle',
  database: 'i-tabler-database',
  document: 'i-tabler-file-text',
  'document-add': 'i-tabler-file-plus',
  dollar: 'i-tabler-currency-dollar',
  'dots-menu': 'i-tabler-dots',
  download: 'i-tabler-download',
  edit: 'i-tabler-pencil',
  emoji: 'i-tabler-mood-smile',
  file: 'i-tabler-file',
  folder: 'i-tabler-folder-open',
  graph: 'i-tabler-trending-up',
  grid: 'i-tabler-grid-3x3',
  home: 'i-tabler-home',
  'info-circle': 'i-tabler-info-circle',
  layers: 'i-tabler-stack-2',
  letter: 'i-tabler-mail',
  list: 'i-tabler-list',
  lock: 'i-tabler-lock',
  login: 'i-tabler-login',
  logout: 'i-tabler-logout',
  menu: 'i-tabler-menu',
  'minus-circle': 'i-tabler-circle-minus',
  monitor: 'i-tabler-device-desktop',
  moon: 'i-tabler-moon',
  palette: 'i-tabler-palette',
  'palette-round': 'i-tabler-brush',
  refresh: 'i-tabler-refresh',
  rocket: 'i-tabler-rocket',
  search: 'i-tabler-search',
  send: 'i-tabler-send',
  settings: 'i-tabler-settings',
  'shield-check': 'i-tabler-shield-check',
  'shield-user': 'i-tabler-shield',
  'shield-warning': 'i-tabler-shield-exclamation',
  'shopping-cart': 'i-tabler-shopping-cart',
  sidebar: 'i-tabler-layout-sidebar',
  spinner: 'i-tabler-loader-2',
  star: 'i-tabler-star',
  sun: 'i-tabler-sun',
  'trend-up': 'i-tabler-trending-up',
  truck: 'i-tabler-truck',
  tuning: 'i-tabler-adjustments-horizontal',
  'user-plus': 'i-tabler-user-plus',
  users: 'i-tabler-users',
  widget: 'i-tabler-layout-grid',
  'zoom-in': 'i-tabler-zoom-in',
  'zoom-out': 'i-tabler-zoom-out',
}
